### PR TITLE
Fix missing data parameter for PATCH requests

### PR DESCRIPTION
**Pull request by jfsso**
The data parameter for PATCH requests was not being passed to axios.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@jfsso thanks a lot for your contribution! 🎉

**Comment by andrii-bodnar** [comment]
Available in the [0.0.2](https://github.com/andrii-bodnar/crowdin-request-action/releases/tag/0.0.2) version

**Comment by jfsso** [comment]
@andrii-bodnar thank for the fast release! verified it works all good in `0.0.2` 👍🏽

**Comment by andrii-bodnar** [comment]
@jfsso apparently, you're the first user of this action, so I would be really happy to receive any feedback 😃

**Comment by jfsso** [comment]
@andrii-bodnar Happy to be the first user and be able to contribute on fixes here :) I've been very satisfied with the results so far, and I especially appreciate the ease with which I can chain steps to create API call sequences using the output of previous steps. Thank you for such a great tool!

**Comment by andrii-bodnar** [comment]
@jfsso great, thanks a lot for the feedback! 🚀

**Pull request merged**
